# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.


main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 20
  - name: Tags
    identifier: tags
    weight: 30
  - name: Academic
    parent: tags
    url: tags/academic/
    weight: 10
  - name: post
    url: post/
    weight: 40
